name: Build and Push Docker Image to Amazon ECR - Storage Server

on:
    push:
#      paths:
#        - "gpt/**"
      branches: [main, release, feature, develop, fix]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ env.ROLE_ARN }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REPOSITORY: sodong-storage

      run: |
        docker build \
        --build-arg OPENAI_KEY=${{ secrets.OPENAI_KEY }} \
        --build-arg REST_API_KEY=${{ secrets.REST_API_KEY }} \
        --build-arg MAX_TOKENS=${{ vars.MAX_TOKENS }} \
        --build-arg TEMPERATURE=${{ vars.TEMPERATURE }} \
        --build-arg TOP_P=${{ vars.TOP_P }} \
        --build-arg N=${{ vars.N }} \
        -t ${{ env.ECR_REPOSITORY }}:latest \
        -f gpt.Dockerfile .
        
        docker tag ${{ env.ECR_REPOSITORY }}:latest ${{ vars.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
        
        docker push ${{ vars.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest